[FE][Feat] #10/소셜로그인-로직 초안
f-lab-edu/dukpool pull request #11
Opened 2023-12-10 13:35 UTC by GeonwooShin

close #10 

- 소셜로그인 관련 로직 초안을 작성했습니다.
- 로컬스토리지 관련 유틸 함수와, 토큰 유틸 함수를 작성했습니다.
- authLayout로 감싸져있는 페이지는 토큰 유무에 따라서 페이지 분기처리를 진행합니다.
- 소셜 로그인 rest api 키를 가짐에 따라 env 파일을 생성하고, webpack에도 env 설정을 추가했습니다.
- 애플리케이션 전체적인 레이아웃 디자인을 수정했습니다.

![ㄴㄴㄴㄴㄴ](https://github.com/f-lab-edu/dukpool/assets/79186378/c45222c0-0df5-43cb-990d-d907d45cc412)

2023-12-10 14:52 UTC, f-lab-jake requested changes

2023-12-10 14:52 UTC, f-lab-jake commented on frontend/src/utils/localstorage.ts
> +  if (typeof window === 'undefined') return undefined;
`if (typeof window === 'undefined')` 요거 SSR할때를 위한 분기인가요?

2023-12-10 14:52 UTC, f-lab-jake commented on frontend/src/utils/token.ts
> +  refreshToken: string | undefined;
refreshToken을 사용하기로 결정한 근거가 궁금합니다

2023-12-10 14:52 UTC, f-lab-jake commented on frontend/src/utils/token.ts
> +const TOKEN_KEY = '@DukpoolToken';
localStorage는 해당 사이트내에서 로컬하기 때문에 네이밍도 로컬하게 하는게 좋습니다.
지금 이런 룰대로면 모든 key들 앞에 @Dukpool을 붙이는게 일관성 있을겁니다.
그렇게 할 의도인가요?

2023-12-10 14:52 UTC, f-lab-jake commented on frontend/src/components/common/Layout/AuthLayout.tsx
> +  }, []);
이걸 훅으로 분리해봅시다.

2023-12-10 15:44 UTC, GeonwooShin commented on frontend/src/utils/token.ts
> +  refreshToken: string | undefined;
일반적으로 accessToken은 유효기간을 짧게 설정하는 것으로 알고있습니다.
따라서 애플리케이션을 이용할 때 유저가 accessToken의 짧은 유효기간으로 인해 반복적인 로그인을 하지않도록
refreshToken을 통해서 accessToken이 만료됐을 때 갱신을 통해 세션을 유지하려는 의도로 사용하려고 했습니다!

2023-12-10 15:45 UTC, GeonwooShin commented on frontend/src/utils/token.ts
> +const TOKEN_KEY = '@DukpoolToken';
현재 localhost에서 작업을 하다보니 이전에 진행했던 프로젝트들의 key들이 남아있어서 별 생각없이 네이밍을 `@DukpoolToken`으로 가져갔는데, 그 부분을 간과한것같습니다!
해당 사이트내에서 로컬하게 가져갈수있도록 `token`이라는 key값을 사용하도록 하겠습니다!

2023-12-10 15:47 UTC, GeonwooShin commented on frontend/src/utils/localstorage.ts
> +  if (typeof window === 'undefined') return undefined;
사실 ssr을 도입한다해도, 로컬스토리지는 클라이언트 단에서 접근할 수 있기 때문에 해당 에러처리는 필요없을 것 같습니다!

2023-12-10 16:00 UTC, GeonwooShin commented on frontend/src/components/common/Layout/AuthLayout.tsx
> +  }, []);
#[795c36f](https://github.com/f-lab-edu/dukpool/pull/11/commits/795c36f0ed9e5ae2bfd74d602f9d0f96e7d5ef5e)

2023-12-11 12:53 UTC, f-lab-jake commented on frontend/src/components/common/Layout/AuthLayout.tsx
> +  }, []);
지금 로그인을 하는 로직은 `useAuthCheck`외에 별도로 분리되어 있죠?

2023-12-11 12:53 UTC, f-lab-jake commented on frontend/src/components/common/Layout/AuthLayout.tsx
> +  }, []);
아직 모듈화가 덜 되어 있다는 이야기입니다.

2023-12-11 15:43 UTC, GeonwooShin commented on frontend/src/components/common/Layout/AuthLayout.tsx
> +  }, []);
`useAuthCheck`외에 로그인 로직이라면 어떤걸 말씀하시는지 알수있나요?!?

2023-12-12 02:57 UTC, f-lab-jake commented on frontend/src/components/common/Layout/AuthLayout.tsx
> +  }, []);
token을 set하는 코드가 별개로 존재하지 않나요?

2023-12-12 03:33 UTC, GeonwooShin commented on frontend/src/components/common/Layout/AuthLayout.tsx
> +  }, []);
token을 set하는 로직은 소셜로그인 리다이렉트 페이지 내에서 진행합니다!

예를들어

```ts
useEffect(() => {
    const code = new URL(window.location.href).searchParams.get('code');
    instance
      .get(`/auth/kakao?code=${code}`)
      .then((response) => {
        const token: Token = {
          accessToken: response.data.accessToken,
          refreshToken: response.data.refreshToken,
        };
        if (token) setToken(token);
      })
      .then(() => router.push('/mypage'))
      .catch((err) => {
        err;
      });
  }, []);
```

리다이렉트 되는 페이지 내에서 위와 같은 로직을 추가하려고 한다면 위의 사항도 useAuthCheck 내에서 함께 관리해야할까요?

2023-12-12 04:07 UTC, f-lab-jake commented on frontend/src/components/common/Layout/AuthLayout.tsx
> +  }, []);
네네 그리고 `setToken`같은게 노출되는건 오히려 안좋습니다. 왜일까요?

2023-12-12 08:24 UTC, GeonwooShin commented on frontend/src/components/common/Layout/AuthLayout.tsx
> +  }, []);
`setToken`이 노출된다면 특정 경우 잘못된 토큰을 로컬스토리지에 추가할 수 있기 때문이라고 생각합니다.

2023-12-17 14:25 UTC, GeonwooShin commented
피드백 수정사항

- 로컬스토리지 유틸함수에서 추가적인 token 관련함수를 생성해서 사용하는 방법에서 그냥 로컬스토리지 유틸 함수 자체를 사용하는 방식으로 수정
- 전역에서 `AuthContext`를 사용하고 `useIsLoggined` 훅 내에서 해당 context api의 `isLoggined` 상태를 받아서 사용하는 것으로 수정
- 에러 바운더리 초안 작성 후 테스트 중, 로그인 상태가 아닌 경우 에러를 throw 하지만 `ErrorBoundary`컴포넌트에서 잡지 못하는 **이슈** 발생

2023-12-18 03:24 UTC, f-lab-jake requested changes
지금 에러 바운더리에 에러가 잡히지 않는 이유는 에러가 에러바운더리 밖에서 발생하고 있기때문입니다. `RouterProvider`의 위치를 살펴보세요.

2023-12-18 03:24 UTC, f-lab-jake commented on frontend/src/hooks/useIsLoggined.ts
> +    throw new Error('The token does not exist or is not valid.');
에러 타입을 하나 만드는게 좋습니다. 그래야 인증실패만 걸러내는 로직이 깔끔합니다. 
https://www.npmjs.com/package/makeerror
요런 라이브러리가 있습니다.

2023-12-18 03:24 UTC, f-lab-jake commented on frontend/src/context/AuthContext.tsx
> +    <AuthContext.Provider value={{ isLoggined }}>
결국엔 `token`이나 `axios` 인스턴스가 필요해질겁니다. 로그인 되었을 경우에 로그인되었다는 사실만 가지고 할수있는게 없죠.

2023-12-18 03:24 UTC, f-lab-jake commented on frontend/src/components/common/ErrorBoundary/index.tsx
> +class ErrorBoundary extends Component<ErrorBoundaryProps, ErrorBoundaryState> {
`componentDidCatch`를 활용해야한다는 사실을 배웠으면 충분합니다.
https://www.npmjs.com/package/react-error-boundary
요걸 사용해봅시다.

2023-12-19 08:40 UTC, f-lab-jake requested changes

2023-12-19 08:40 UTC, f-lab-jake commented on frontend/src/components/common/ErrorFallback/index.tsx
>  };
현재 구현대로면 로그인 안된상태로 로그인된 페이지에 들어갔을때(url을 통해서라던가) '오류가 발생했습니다'란 메시지를 띄웁니다. 그런데 그만큼 심각한 상황은 아니잖아요? 좀더 잘 설명할수 있을겁니다.

2023-12-19 08:40 UTC, f-lab-jake commented on frontend/src/components/common/ErrorFallback/index.tsx
> +    if (error.message === INVALID_TOKEN_ERROR) {
요건 굉장히 위험한 방법입니다. 왜그럴까요?
대안으로는 https://www.npmjs.com/package/makeerror 등이 있습니다.

2023-12-19 08:52 UTC, GeonwooShin commented on frontend/src/components/common/ErrorFallback/index.tsx
>  };
현재 로그인이 안된 상태로 로그인이 필요한 페이지에 들어갔을때는 `useEffect`에서 `INVALID_TOKEN_ERROR` 에러가 발생해서 로그인 페이지로 이동합니다!

그 이외의 에러가 발생하는 경우에 `오류가 발생했습니다`라는 메시지를 띄웁니다

이런 경우에도 오류라는 명칭보다는 다른 명칭을 사용하는것이 좋을까요?

2023-12-19 08:54 UTC, GeonwooShin commented on frontend/src/components/common/ErrorFallback/index.tsx
> +    if (error.message === INVALID_TOKEN_ERROR) {
위와 같이 상수로 관리한다면 이후에 에러 메시지가 변경되는 경우 모든 관련 코드를 업데이트해야하기 때문일까요?

2023-12-19 11:44 UTC, f-lab-jake commented on frontend/src/components/common/ErrorFallback/index.tsx
> +    if (error.message === INVALID_TOKEN_ERROR) {
에러메시지는 디버깅을 위해 존재하는 것으로, 편의에 따라 언제든 변경할수 있을것으로 기대됩니다.
지금 이 코드는 주민번호를 냅두고 이름으로 사람을 확인하는 것과 같습니다.

2023-12-19 11:45 UTC, f-lab-jake commented on frontend/src/components/common/ErrorFallback/index.tsx
>  };
로그인이 안되었고 그래서 로그인 페이지로 리다이렉트한다고 하는게 좋겠습니다.
또 거기서 로그인되어서 원래 하려던 동작을 이어서할수있게 하면 더 좋겠죠.

2023-12-19 13:26 UTC, GeonwooShin commented on frontend/src/components/common/ErrorFallback/index.tsx
>  };
앗 멘토님 ErrorFallback 컴포넌트에서 로그인 페이지로 이동하는 부분 로직은 다음과 같은 순서로 이루어집니다!

1. `mypage` 페이지로 접속합니다.
2. `mypage` 내에서는 `useIsLoggined` 훅을 사용합니다.
3. `useIsLoggined` 에서는 유저의 로그인 유무를 확인하고 로그인이 되어있지 않다면 `UnAuthorized Error`를 던집니다.
4. 에러가 `ErrorBoundary`에서 걸리고 `ErrorFallback` 컴포넌트에서 `error.message`가 `UnAuthorized Error`라면 로그인 페이지로 이동합니다.

`오류가 발생했습니다. 재시도 해주세요` 이 부분은 `react-query`와 함께 http 요청 시 사용하는 부분입니다!

2023-12-19 13:29 UTC, GeonwooShin commented on frontend/src/components/common/ErrorFallback/index.tsx
> +    if (error.message === INVALID_TOKEN_ERROR) {
이해했습니다

`makeerror` 라이브러리에 대한 레퍼런스가 없어서 사용법을 찾기가 어렵네요.. 더 찾아보겠습니다

2023-12-20 02:15 UTC, f-lab-jake commented on frontend/src/components/common/ErrorFallback/index.tsx
> +    if (error.message === INVALID_TOKEN_ERROR) {
https://www.npmjs.com/package/make-error

얘는 문서가 좀더 자세하네요. 둘다 거의 똑같을겁니다. 이쪽을 써도 좋습니다.

2023-12-20 02:23 UTC, f-lab-jake commented on frontend/src/components/common/ErrorFallback/index.tsx
>  };
네네 이해했습니다. 그런데 지금 이동하기 전에 저 오류 페이지가 잠깐 보이지 않나요? 언제나 보이지 않을거라는게 지금 코드로 보장이 되진 않습니다. 최소한 `null`을 리턴하는등의 처리를 하는게 좋겠습니다. 

아니면 그냥 `useEffect`로 안감싸도 됩니다. https://github.com/facebook/react/issues/5591#issuecomment-333493217
`resetErrorBoundary`가 `setState`인 셈이란 말이죠.

2023-12-21 08:57 UTC, GeonwooShin commented
피드백 수정사항

- makeError 라이브러리를 사용하여 커스텀 에러를 생성하고 명시적인 에러를 통해 에러처리 [92c7d0d](https://github.com/f-lab-edu/dukpool/pull/11/commits/92c7d0d4552800e35d590115b539a7c50a828d4a) , [bf67800](https://github.com/f-lab-edu/dukpool/pull/11/commits/bf6780070f3f4c2c19d518fd03524b8643f89dc1)
- AuthContext 내에서 인증 관련 로직을 모두 처리할 수 있도록 수정, token이 변경되면 인스턴스도 새로 생성 [5032ca5](https://github.com/f-lab-edu/dukpool/pull/11/commits/5032ca55812350ac46f79bed94f84d3f981fbf8d)
- axios instance를 사용할 수 있는 useClient 훅을 생성 [2408f95](https://github.com/f-lab-edu/dukpool/pull/11/commits/2408f95b76edadfb749c5630236bd93c0df1e529)
- 전역의 axios 인스턴스를 사용하지 않고, token에 따라 새로운 인스턴스를 사용할 수 있도록 useClient의 인스턴스를 사용하도록 api 모듈화 [afb7989](https://github.com/f-lab-edu/dukpool/pull/11/commits/afb7989a1239fec14a195655d16991d3c401ec4d)

2023-12-21 13:24 UTC, f-lab-jake requested changes

2023-12-21 13:24 UTC, f-lab-jake commented on frontend/src/apis/auth/authApi.ts
> +const authApi = (): AuthApis => {
`authApi`도 일종의 훅이죠?

2023-12-21 13:24 UTC, f-lab-jake commented on frontend/src/context/AuthContext.tsx
> +  }, [token]);
더 나은 방법을 찾아봅시다.

2023-12-21 13:24 UTC, f-lab-jake commented on frontend/src/context/AuthContext.tsx
> +    navigate('/login');
/login 페이지에 로그인 로직이 없던데 지금 실제로 로그인을 어디서 하는거지요?

2023-12-21 14:52 UTC, GeonwooShin commented on frontend/src/context/AuthContext.tsx
> +    navigate('/login');
로그인은 소셜 로그인 방식으로 채택해서

`Login` 페이지 내에서는 카카오 리다이렉트 페이지로 이동하고
`Kakao` 페이지에서 카카오 redirect url에 전달되는 인가코드를 통해 다음과 같은 코드로 로그인을 진행합니다!

ex)
```ts
  useEffect(() => {
    const code = new URL(window.location.href).searchParams.get('code');
    instance
      .get(`/oauth2/kakao?code=${code}`)
      .then((response) => {
        const token: Token = {
          accessToken: response.data.accessToken,
          refreshToken: response.data.refreshToken,
          roles: response.data.roles,
        };
        if (token) setToken(token);
      })
      .then(() => router.push('/home'))
      .catch((err) => {
        err;
      });
  }, []);
```

2023-12-21 14:53 UTC, GeonwooShin commented on frontend/src/apis/auth/authApi.ts
> +const authApi = (): AuthApis => {
네이밍도 use를 붙여 훅임을 명시해야겠네요!

2023-12-21 14:54 UTC, GeonwooShin commented on frontend/src/context/AuthContext.tsx
> +  }, [token]);
토큰의 변경사항에 따라 새로운 인스턴스를 생성해서 전달하려고 했는데, 혹시 더 좋은 방법은 어떤 식으로 접근을 해야할까요?

2023-12-21 15:15 UTC, GeonwooShin commented on frontend/src/context/AuthContext.tsx
> +    navigate('/login');
`Kakao` 페이지 내에서

```ts
const { login } = useContext(AuthContext);
```
위와 같이 꺼내서 사용할 수 있도록

```ts
const login = async (code: string) => {
    const { token } = await client.get(`/oauth/kakao?code=${code}`);
    setToken(token);
};
```

`AuthContext` 내에서 이런식으로 관리하는게 좋을까요?

2023-12-22 00:58 UTC, f-lab-jake commented on frontend/src/context/AuthContext.tsx
> +    navigate('/login');
넵 딱 좋습니다. 제가 제안드리려던 방법이었습니다. AuthContext는 token의 로컬스토리지에의 싱크까지 캡슐화해야합니다

2023-12-22 00:58 UTC, f-lab-jake commented on frontend/src/context/AuthContext.tsx
> +  }, [token]);
useMemo를 활용하봅시다

2023-12-22 00:59 UTC, f-lab-jake commented on frontend/src/apis/auth/authApi.ts
> +const authApi = (): AuthApis => {
네네. 일단 그렇게하먼 규칙은 지킨셈이죠. 그런데 좀 번거롭죠? jotai tanstackquery를 공부해봅시다

2023-12-22 07:57 UTC, GeonwooShin commented
피드백 사항 반영했습니다!

useMemo를 사용하여 토큰 변경시에만 Axios 인스턴스를 새로 생성하도록 수정했습니다!

2023-12-22 10:55 UTC, GeonwooShin commented
피드백 사항 반영했습니다!

`useMemo`를 사용하여 토큰 변경시에만 Axios 인스턴스를 새로 생성하도록 수정했습니다.

`token`의 `initialState`를 로컬스토리지에서 토큰 키를 통해 가져온 토큰값으로 지정하고
초기에 로그인 이전에는 토큰 값이 `null`이기 때문에 `client`를 생성할 때 `token`의 유무에 따라 헤더를 분기처리했습니다.

2023-12-25 04:31 UTC, f-lab-jake requested changes

2023-12-25 04:31 UTC, f-lab-jake commented on frontend/src/context/AuthContext.tsx
> +      headers: headers,
잘했습니다. 그런데 요부분은 punning을 해줍시다.

2023-12-25 04:31 UTC, f-lab-jake commented on frontend/src/context/AuthContext.tsx
> +      headers: headers,
punning은 린터로 설정해놓는게 좋습니다.

2023-12-25 13:31 UTC, GeonwooShin commented on frontend/src/context/AuthContext.tsx
> +      headers: headers,
말씀하신 punning이 headers 객체를 별도로 정의하지 않고 직접 객체 리터럴에서 해당 속성을 동적으로 생성하여 사용하도록 하는거라고 봐도될까요??

2023-12-25 13:37 UTC, GeonwooShin commented
`headers` 객체를 별도로 정의하지 않는 방식으로 수정했습니다! `punning` 관련해서 찾아보니 구조분해할당과 관련된 내용인것같아서 `eslint`에 구조분해할당을 사용할수 있도록 `prefer-destucturing` 설정을 추가했습니다!

2023-12-26 02:17 UTC, f-lab-jake commented
punning얘기는 단순히 `headers: headers,` 대신에 그냥 `headers,`로 쓰란 얘기였습니다. 린터가 알아서 하도록 설정해둡시다.

2023-12-26 02:17 UTC, f-lab-jake approved these changes

2023-12-26 05:51 UTC, merged