[FE][Feat] #17/ 덕질 자랑 & 덕질 토크 카드 컴포넌트 및 스켈레톤 작성
f-lab-edu/dukpool pull request #19
Opened 2024-01-06 06:29 UTC by GeonwooShin

![Jan-06-2024 15-28-25](https://github.com/f-lab-edu/dukpool/assets/79186378/1944c003-d453-4faa-a5f9-735de3cdd295)

- 레이아웃을 대대적으로 수정했습니다.
- 모바일 버전에서 `100vh` 일 때 스크롤 문제로 인해 `innerHeight`를 계산하여 동적으로 뷰포트의 높이를 결정할 수 있도록 `useInnerHeight` 훅을 생성하여 사용할 수 있도록 했습니다.
- 유저들의 덕질 자랑, 유저들의 최근 토크 컴포넌트를 작성하기 위한 `ArticleCard`와 `TalkCard` 카드 컴포넌트를 작성했습니다.
- carousel을 구현하기 위해 `react-slick` 라이브러리를 도입했고 각각 `ArticleCard`와 `TalkCard`를 사용하여 carousel을 구현한 `RecentArticleCards`와 `RecentTalkCards` 컴포넌트를 작성했습니다.
- 모바일 버전에서는 carousel이 아닌 스크롤을 통해 구현하기 위해 `ArticleCard`와 `TalkCard`를 사용하여 모바일 버전의 컴포넌트를 작성했습니다.
- 각각 컴포넌트에 해당하는 모든 스켈레톤 컴포넌트를 작성했습니다.
- 홈 화면에서는 `DukpoolArticles`와 `DukpoolTalks` 컴포넌트를 통해 구현을 완료했습니다.
- `input`에 기본적인 역할을 하는 함수들을 분리하기 위해 `reducer` 함수로 분리했습니다

2024-01-06 10:13 UTC, f-lab-jake requested changes

2024-01-06 10:13 UTC, f-lab-jake commented on frontend/src/components/ArticleCard/index.tsx
> +                  src={userProfile.image ? userProfile.image : placeholderImage}
`??`를 써봅시다.

2024-01-06 10:13 UTC, f-lab-jake commented on frontend/src/components/ArticleCard/index.tsx
> +    commentCount,
props가 너무 많은게 좀 불안합니다.
`children` props로 확장성을 챙길수있습니다.

2024-01-06 10:13 UTC, f-lab-jake commented on frontend/src/components/common/Skeleton/ArticleCardSkeleton.tsx
> +  return (
사이에 내용없을땐 return 빼서 더 간결하게 해봅시다. vs code 기능으로 쉽게 바꿀수있어요.

2024-01-06 10:13 UTC, f-lab-jake commented on frontend/src/components/home/RecentArticleCards/index.tsx
> +          ></ArticleCard>
spread operator를 활용해 간결하게 만듭시다.

2024-01-07 07:06 UTC, GeonwooShin commented
- Article과 Talk에 해당하는 `SliderSkeleton`과 `MobileCardSkeleton`을 컴포넌트로 각자 관리했던 부분을 `ArticleSkelton`, `TalkSkeleton` 내에서 분기처리로 관리하도록 수정했습니다.

`MobileRecentArticleCards`
```
const MobileRecentArticleCards = memo(() => {
  const { data: articles } = useGetAllArticles();
  return ...
});
`;
```

`RecentArticleCards`
```
const RecentArticleCards = memo(() => {
  const { data: articles } = useGetAllArticles();
  return ...
});
```

`DukpoolArticles`
```
const DukpoolArticles = memo(() => {
  const { isMobile } = useMediaQuery();
  return (
    <StyledSection>
      <StyledSectionTitle>유저들의 최근 덕질</StyledSectionTitle>
      {isMobile ? (
        <Suspense fallback={<MobileArticleCardsSkeleton />}>
          <MobileRecentArticleCards />
        </Suspense>
      ) : (
        <Suspense fallback={<ArticleSliderSkeleton />}>
          <RecentArticleCards />
        </Suspense>
      )}
    </StyledSection>
  );
});
```

- 기존에 `RecentMobileTalkCards`와 `RecentTalkCards` 그리고 `RecentMobileArticleCards`와 `RecentArticleCards`로 나누어서 내부에서 `useQuery`를 사용하도록 했는데 반응형으로 데스크탑 화면에서 모바일 화면으로 변경시에 또다시 data fetching이 일어나는 버그가 있어서 

`RecentArticleCards`
```
const RecentArticleCards = memo(() => {
  const { isMobile } = useMediaQuery();
  const { data: articles } = useGetAllArticles();
  return isMobile ? (
    <StyledWrapper>
      {articles?.map((article: ArticleProps) => (
        <ArticleCard {...article} key={article.id}></ArticleCard>
      ))}
    </StyledWrapper>
  ) : (
    <StyledSlider {...SliderOption}>
      {articles?.map((article: ArticleProps) => (
        <ArticleCard {...article} key={article.id}></ArticleCard>
      ))}
    </StyledSlider>
  );
});
```

`DukpoolArticles`
```
const DukpoolArticles = memo(() => {
  return (
    <StyledSection>
      <StyledSectionTitle>유저들의 최근 덕질</StyledSectionTitle>
      <Suspense fallback={<ArticleSkeleton />}>
        <RecentArticleCards />
      </Suspense>
    </StyledSection>
  );
});
```

다음과 같이 상위에서 처리할 수 있도록 수정했습니다.

- spread operator를 사용하는 방식으로 수정했습니다

2024-01-07 11:11 UTC, f-lab-jake requested changes

2024-01-07 11:11 UTC, f-lab-jake commented on frontend/src/components/common/Skeleton/ArticleSkeleton.tsx
> +      ))}
공통된 부분은 변수로 뺍시다.

2024-01-07 11:11 UTC, f-lab-jake commented on frontend/src/components/home/RecentTalkCards/index.tsx
>    const { data: talks } = useGetAllTalks();
`talks`가 `undefined`일 때는 어떤 경우인건가요? 아직 로딩이 안된건가요?

2024-01-07 13:41 UTC, GeonwooShin commented on frontend/src/components/home/RecentTalkCards/index.tsx
>    const { data: talks } = useGetAllTalks();
옵셔널 체이닝 말씀이신가요!?

2024-01-07 14:42 UTC, GeonwooShin commented on frontend/src/components/common/Skeleton/ArticleSkeleton.tsx
> +      ))}
네 알겠습니다!

2024-01-07 15:36 UTC, f-lab-jake commented on frontend/src/components/home/RecentTalkCards/index.tsx
>    const { data: talks } = useGetAllTalks();
`talks`가 `undefined`란 값을 가질때, 그게 어떤 의미냐는 질문이었습니다.

2024-01-07 16:02 UTC, GeonwooShin commented on frontend/src/components/home/RecentTalkCards/index.tsx
>    const { data: talks } = useGetAllTalks();
죄송합니다 멘토님 질문을 잘 이해하지 못한것같습니다 ㅠㅠ `useQuery` 훅을 통해서 가져온 데이터인 `talks`가 `undefined`값을 가지게되나요?

2024-01-09 06:22 UTC, GeonwooShin commented
- 공통된 부분을 변수로 분리하여 `useMemo`를 사용하여 메모이제이션을 통해 관리하도록 수정했습니다. [c6d4da0](https://github.com/f-lab-edu/dukpool/pull/19/commits/c6d4da0de5f9aa971764b46a4dd61963b09ed37f)
- `assert` 함수를 사용하여 타입 단언을 통해 쿼리 사용시 `response`의 타입이 `undefined`를 피하도록 수정했습니다 [0ecfcb0](https://github.com/f-lab-edu/dukpool/pull/19/commits/0ecfcb0f50a5a9808838d5162ff245c50d8e6ed4)
- `refreshToken`이 쿠키로 내려오는 방식으로 수정되어 `instance`에 `withCredentials` 옵션을 추가했습니다. [111dd0a](https://github.com/f-lab-edu/dukpool/pull/19/commits/111dd0a2a4e521f3db179e2b33bcb02ea34207b0)

2024-01-09 06:28 UTC, f-lab-jake requested changes

2024-01-09 06:28 UTC, f-lab-jake commented on frontend/src/components/ArticleCard/index.tsx
> +      <StyledList key={id}>
여기 `key`넣는건 의미가 없을텐데요?

2024-01-09 06:28 UTC, f-lab-jake commented on frontend/src/components/common/Skeleton/TalkSkeleton.tsx
> +  const SkeletonArray = useMemo(
그냥 전역변수로 빼도되겠죠?

2024-01-09 06:28 UTC, f-lab-jake commented on frontend/src/components/home/RecentArticleCards/index.tsx
> +  const ArticleCards = useMemo(
`deps`에 `articles`가 있어야겠죠.
그냥 `useMemo`를 안쓰는걸 추천합니다.

2024-01-09 06:28 UTC, f-lab-jake commented on frontend/src/hooks/useGetQueries.ts
> +  return useQuery<TalkProps[], Error>(['useGetAllTalks'], () => getAllTalks());
타입 명시 하지말고 그냥 `getAllTalks`로부터 유추되도록 합시다.
그리고 `() => getAllTalks`말고 `getAllTalks`로 충분합니다.

2024-01-09 09:55 UTC, GeonwooShin commented
- 스켈레톤 UI의 공통 부분을 전역 변수로 관리하도록 수정했습니다
- useQuery의 타입 명시를 제거하고, queryFn의 타입을 명시하여 queryFn의 타입을 통해 useQuery가 타입을 추론하도록 수정했습니다.

2024-01-10 13:17 UTC, GeonwooShin commented
- 공통된 element 부분을 분리하고 컴포넌트 변수명을 사용했던 부분을 수정했습니다.

2024-01-11 02:43 UTC, f-lab-jake approved these changes

2024-01-11 05:01 UTC, merged