[FE][Feat] #26/ react-hook-form 도입 및 덕질자랑 아티클 추가, 수정 페이지 구현
f-lab-edu/dukpool pull request #29
Opened 2024-01-19 12:25 UTC by GeonwooShin

✅ 주된 작업 사항

1. 기존 `jotai`를 통해 전역으로 `form state`를 관리하던 부분을 `react-hook-form`을 도입하여 `form`을 관리하도록 수정했습니다.
2. 서버에서 아티클을 받아올 때 `response` 값 중 이미지가 `string url`로 넘어오는 부분을 고려하여 수정 페이지에서 `patch` 요청시 이미지를 다시 파일 형태로 보내줄 수 있게 `convertURLtoFile` 유틸 함수를 작성하여 사용하도록 했습니다.
3. 덕질자랑 아티클 추가 및 수정 페이지에서 각각 `useForm`에 `defaultValues`를 적용하여 사용되는 `Title`, `Tags`, `Content`, `Images` 컴포넌트를 공통적으로 사용할 수 있도록 수정했습니다.
4. `useGetAllArticles` 훅의 쿼리키로 `sortType`을 추가하여 새로 작성한 `Dropdown` 컴포넌트 내부에서 `props`로 `sortType` 과 `setSortType`을 받아 아티클의 정렬 옵션을 관리하여 state 변경시 api 재요청하도록 수정했습니다

2024-01-20 02:36 UTC, f-lab-jake requested changes

2024-01-20 02:36 UTC, f-lab-jake commented on frontend/src/components/article/ArticleForm/Images.tsx
> +  imageList: any[];
`images`랑 `imageList`같은 변수명을 동시에 쓰지맙시다. 똑같은 뜻인데 다르게 쓴것처럼 보입니다.
아니면 `imageList`의 의미를 정확히 설명할수 있으면 괜찮습니다.

2024-01-20 02:36 UTC, f-lab-jake commented on frontend/src/components/article/ArticleForm/Images.tsx
>      }
그냥  `...files`해도 됩니다.

2024-01-20 02:36 UTC, f-lab-jake commented on frontend/src/components/article/ArticleForm/Tags.tsx
> +    const updatedTags = tagList.filter((tag: any) => tag !== tagToDelete);
함수 인자에 `any`달지 마세요.

2024-01-20 02:36 UTC, f-lab-jake commented on frontend/src/components/article/EditArticle/DukpoolEditArticle.tsx
> +    const formData = new FormData();
파일 빼고는 통째로 json으로 전달하는 방법도 고려해보았나요? 이게 필드가 많아지거나 nesting 구조가 생기면 귀찮아집니다.

2024-01-20 02:36 UTC, f-lab-jake commented on frontend/src/components/article/EditArticle/DukpoolEditArticle.tsx
> +      )}
`title` 관련 에러가 "제목을 최소 5자 이상 입력해주세요." 요거 밖에 없다는 보장이 있을때만 맞는 코드입니다.

2024-01-20 02:36 UTC, f-lab-jake commented on frontend/src/components/common/Dropdown/index.tsx
> +  { id: 3, type: 'mostComment', name: '댓글 많은 순' },
그냥 `type`을 `id`로 쓰는게 어떨까요?

2024-01-20 14:56 UTC, GeonwooShin commented
- 인증 로직을 전역 상태로 관리하기 위해 `authAtom`을 생성했습니다.
- `Jwt-decode` 라이브러리를 통해 토큰값으로부터 유저의 `id`를 추론할 수 있도록 했습니다.
- `react-hook-form`을 사용하면서 폼 필드마다 존재할 수 있는 에러타입마다 분기가 가능하도록 수정했습니다.

2024-01-21 06:32 UTC, GeonwooShin commented on frontend/src/components/article/EditArticle/DukpoolEditArticle.tsx
> +    const formData = new FormData();
백엔드 개발자분과 한 번 의논해보도록 하겠습니다!

2024-01-21 12:08 UTC, f-lab-jake approved these changes

2024-01-21 12:08 UTC, f-lab-jake commented on frontend/src/components/article/EditArticle/DukpoolEditArticle.tsx
> +  images: (string | File)[];
변경전과 차이가 뭔지 설명해봅시다

2024-01-21 14:41 UTC, GeonwooShin commented on frontend/src/components/article/EditArticle/DukpoolEditArticle.tsx
> +  images: (string | File)[];
변경 전에는 string배열 또는 File 배열이어서 서버에서 받은 이미지 url string과 File을 배열에  함께 담게되면 에러가 발생했는데
string 또는 File이 담긴 배열로 타입을 수정하여 이미지 string url과 File을 함께 배열에 담을수있도록 수정했습니다!

2024-01-22 08:22 UTC, f-lab-jake requested changes

2024-01-22 08:22 UTC, f-lab-jake commented on frontend/src/components/article/ArticleForm/Content.tsx
> +};
이런 props가 필요하단게 좀 이상하죠?
context로 내려주는게 있습니다.

2024-01-22 10:10 UTC, GeonwooShin commented on frontend/src/components/article/ArticleForm/Content.tsx
> +};
아 하위 컴포넌트에서 필드와 연결가능하도록 `react-hook-form` 자체에서 `useFormContext`를 제공하네요!
이 부분 수정하도록 하겠습니다! 감사합니다!

2024-01-22 11:32 UTC, GeonwooShin commented on frontend/src/components/article/ArticleForm/Content.tsx
> +};
와 useFormContext 사용하니까 기존 코드에서 훨씬 깔끔해졌습니다!

2024-01-22 14:17 UTC, GeonwooShin commented
- 기존에 register를 props로 전달하고 있던 로직을 react-hook-form의 useFormContext를 사용하는 방식으로 수정했습니다 [e878c9b](https://github.com/f-lab-edu/dukpool/pull/29/commits/e878c9b719044493aded1523864b7d88590f2550)
- useFromContext를 사용하기 위해 FormProvider를 사용하도록 수정했습니다. [d4582ce](https://github.com/f-lab-edu/dukpool/pull/29/commits/d4582cee3f3b188bb663c24a9a1b68a014dff159)
- 덕질자랑과 덕질토크 상세 아티클에 동일한 컴포넌트가 사용되어 공통 컴포넌트로 사용하도록 파일 이름을 수정하고 폴더 경로를 수정했습니다. [c264179](https://github.com/f-lab-edu/dukpool/pull/29/commits/c2641799bd9572f27440cd33a9cbd98bb349ca56)
- 덕질 토크, 덕질토크 아티클 상세, 덕질 토크 아티클 등록, 덕질 토크 아티클 수정 페이지를 구현했습니다. [eb41d8b](https://github.com/f-lab-edu/dukpool/pull/29/commits/eb41d8b473510b24d0fba28b3ff93a9f5eff97f7)

2024-01-22 14:40 UTC, f-lab-jake approved these changes

2024-01-22 14:51 UTC, merged