[FE][Feat] #33/ 검색 페이지 구현 및 덕질자랑 & 덕질토크 카드 반응형 디자인 크기 수정
f-lab-edu/dukpool pull request #35
Opened 2024-01-25 11:40 UTC by GeonwooShin

- 덕질자랑 카드 및 덕질토크 카드의 크기를 min-width를 통해 반응형으로 수정했습니다.
- 검색 기능에 필요한 컴포넌트 및 스켈레톤 UI를 구현하고 검색 페이지를 구현했습니다.

close #33

2024-01-26 07:14 UTC, f-lab-jake requested changes

2024-01-26 07:14 UTC, f-lab-jake commented on frontend/src/components/common/Input/index.tsx
>  const Input = memo(() => {
common의 `Input` 컴포넌트가 왜 검색기능과 엮여있는지 잘 모르겠습니다.

2024-01-26 07:14 UTC, f-lab-jake commented on frontend/src/components/common/Skeleton/SearchSkeleton.tsx
> +const ArticleSkeletonArray = Array.from({ length: 8 }).map((_, idx) => (
`range`씁시다

2024-01-26 07:14 UTC, f-lab-jake commented on frontend/src/components/home/RecentTalkCards/index.tsx
> +      {talks.map((talk: TalkPostProps) => (
타입 명시 빼고 추론되도록 냅두는게 낫습니다.

2024-01-26 09:12 UTC, GeonwooShin commented on frontend/src/components/common/Input/index.tsx
>  const Input = memo(() => {
그러고보니 공통컴포넌트라고 만들어놓고 검색 기능에서 사용하고 있었네요, 이렇게 사용하면 공통 컴포넌트로 만들어둔 의미가 없어지는 것이니 수정하도록 하겠습니다!

`Input` 컴포넌트를 좀 더 확장성있게 만들고, `Input` 컴포넌트를 사용해서 검색기능과 엮어 사용할 수 있도록 수정하도록 하겠습니다!

2024-01-26 09:15 UTC, GeonwooShin commented on frontend/src/components/common/Skeleton/SearchSkeleton.tsx
> +const ArticleSkeletonArray = Array.from({ length: 8 }).map((_, idx) => (
`lodash`의 `range` 함수를 사용하는 방식으로 수정하겠습니다!

2024-01-26 09:15 UTC, GeonwooShin commented on frontend/src/components/home/RecentTalkCards/index.tsx
> +      {talks.map((talk: TalkPostProps) => (
이 부분 자꾸 간과하는것같습니다 ㅠㅠ 수정하겠습니다!

2024-01-26 19:21 UTC, GeonwooShin commented
- `Input`과 `TextArea` 컴포넌트의 확장성을 고려하여 수정했습니다.
- `Form` 내에서 사용되는 `Input`과 `TextArea`의 특성을 고려하여 컴포넌트 내부에서 `useFormContext`를 사용했고, 상위 `FormProvider`에서 관리되도록 수정했습니다.
- 기존 `Input`에 검색 기능을 포함했던 부분을 수정하고 검색 기능을 담당하는 `SearchBar` 컴포넌트를 따로 생성하여 검색 기능을 담당하는 부분에서 사용하도록 수정했습니다.
- `skeleton UI`를 구현함에 있어서 `Array.from`을 사용하던 부분을 `lodash`의 `range` 함수를 사용하는 방안으로 수정했습니다.

2024-01-27 03:14 UTC, f-lab-jake approved these changes

2024-01-27 06:11 UTC, merged