[FE][Feat] #36/ 마이페이지 구현
f-lab-edu/dukpool pull request #37
Opened 2024-01-28 14:49 UTC by GeonwooShin

- 마이페이지에 필요한 `MyInfo`, `MyPosts` 두 컴포넌트를 작성하여 마이페이지를 구현했습니다.
- `MyInfo` 컴포넌트에서는 닉네임 수정을 위해 `useDebounce`를 사용하여 `debouncedValue`를 관리하고 `queryKey`로 `debouncedValue`를 추가하여 닉네임 validation 체크를 진행하도록 구현했습니다.

2024-01-28 16:52 UTC, f-lab-jake requested changes

2024-01-28 16:52 UTC, f-lab-jake commented on frontend/src/components/common/Skeleton/ArticleGridSkeleton.tsx
> +const ArticleSkeletonArray = range(8).map((_, idx) => (
요런거 이름을 camelCase로 하세요. 컴포넌트가 아니잖아요?

2024-01-28 16:52 UTC, f-lab-jake commented on frontend/src/components/mypage/MyInfo.tsx
> +  const debouncedValue = useDebounce(nicknameValue, 200);
`nickname`과 `debouncedNickname`이 낫습니다.
어떤 명명 체계가 좋은지 판단할땐 새로 변수가 추가될때도 기능하는지를 생각해보면 도움이 됩니다.

2024-01-28 16:52 UTC, f-lab-jake commented on frontend/src/hooks/usePostMutations.ts
> +    mutationFn: (nickname: string) => postNickname(nickname),
그냥 `postNickname`하면 되겠죠?

2024-01-28 16:52 UTC, f-lab-jake commented on frontend/src/pages/MyPage.tsx
>    useToken();
무슨 의도인가요?

2024-01-28 17:53 UTC, GeonwooShin commented on frontend/src/hooks/usePostMutations.ts
> +    mutationFn: (nickname: string) => postNickname(nickname),
이 부분이 자꾸 헷갈리는것같습니다 ㅠㅠ

2024-01-28 18:01 UTC, GeonwooShin commented on frontend/src/pages/MyPage.tsx
>    useToken();
`useToken` 훅 내에서는 

```ts
const useToken = () => {
  const { isLoggined, token } = useContext(AuthContext);
  if (!isLoggined) {
    throw new UnAuthorizedError('UnAuthorized');
  }
  return token;
};
```

위와 같이 로그인 상태가 아니라면 `UnAuthorizedError`를 `throw`함으로써 `ErrorBoundary`에서 에러가 잡혀 로그인 페이지로 이동시켜주고 있습니다!

따라서 마이페이지 접근시 로그인 상태가 아니라면 로그인 페이지로 이동하게끔 하는 역할을 담당합니다.
생각해보니까 `token`을 사용하지않는데 네이밍을 `useToken`이라고 한게 이상하네요.

따로 토큰을 꺼내서 사용할 일이 없고 로그인상태를 확인하는 훅이니까 `useLoginStatus`가 좀 더 적당할까요?

2024-01-29 01:57 UTC, f-lab-jake commented on frontend/src/pages/MyPage.tsx
>    useToken();
아 사실 이런 의도일거라 짐작은 했습니다. 저도 비슷한 용도로 쓴적이 있거든요.
그런데 저게 없더라도 어차피 `MyInfo`등의 child 컴포넌트로 부터 unauthorized에러가 떨어질거라면 빼도 괜찮을 겁니다.
그게 아닌 경우도 있긴한데 이경우는 아닌거 같네요.

굳이 저렇게 `throw new UnAuthorizedError('UnAuthorized');` 이렇게 뺄필욘없고 `useToken()` 이렇게 써도 괜찮습니다.

2024-01-29 06:51 UTC, GeonwooShin commented on frontend/src/pages/MyPage.tsx
>    useToken();
네 `MyInfo`와 `MyPosts` 컴포넌트의 상위에서 `UnAuthorized`에러가 떨어지도록 했으니 `useToken`을 사용하는 방식으로 가져가겠습니다!

2024-01-29 07:52 UTC, f-lab-jake commented on frontend/src/pages/MyPage.tsx
>    useToken();
어 이경우엔 `useToken`이 따로 없더라도 잘 돌아갈거같단 얘끼였어요. 어차피 `MyInfo` `MyPosts` 에서 내부적으로 `useToken` 호출할테니까요. 아닌가요?

2024-01-29 07:58 UTC, GeonwooShin commented on frontend/src/pages/MyPage.tsx
>    useToken();
`MyInfo`와 `MyPosts`에서는 내부적으로 `useToken`을 호출하고 있지는 않습니다!

`Mypage` 페이지에서 `MyInfo`와 `MyPosts`컴포넌트를 사용하고 있고, `MyPage` 페이지에서 `useToken`을 호출하고 있는 방식으로 사용하고있었습니다!

2024-01-29 07:59 UTC, f-lab-jake commented on frontend/src/pages/MyPage.tsx
>    useToken();
`useClient`를 쓸테니 `useToken`을 쓰는셈 아닌가요?

2024-01-29 08:17 UTC, GeonwooShin commented on frontend/src/pages/MyPage.tsx
>    useToken();
아 `useClient`는

```ts
import { useContext } from 'react';
import { AuthContext } from '@context/AuthContext';
import { UnAuthorizedError } from '@utils/errors';

const useClient = () => {
  const { client } = useContext(AuthContext);
  if (!client) {
    throw new UnAuthorizedError('UnAuthorized');
  }
  return client;
};

export default useClient;
```

위와 같이 사용하고 있었는데 useToken을 쓰는 방식과 같게 하기 위해서는

```ts
import { useContext } from 'react';
import { AuthContext } from '@context/AuthContext';
import { UnAuthorizedError } from '@utils/errors';

const useClient = () => {
  const { isLoggined, client } = useContext(AuthContext);
  if (!isLoggined) {
    throw new UnAuthorizedError('UnAuthorized');
  }
  return client;
};

export default useClient;
```

이렇게 수정하는게 맞겠네요!

근데 이런경우에는 모든 api를 `useClient`를 사용하여 리턴받은 `client`를 통해 http요청을 진행하고 있는데, 로그인이 필요하지 않은 api에 대해서도 `UnAuthorized` 에러가 발생하게 됩니다!

2024-01-30 09:25 UTC, GeonwooShin commented
- `authAtom` 내부에서 인증 토큰을 헤더에 담은 `axios instance`와 일반 `axios instance`를 분리하여 관리하도록 수정했습니다.
- 기존에 `article` , `talk`, `auth`로 분리한 `api`들을 `usePublicApi`, `useTokenApi`로 인증이 필요한 api, 인증이 필요하지 않은 api를 분리하여 내부에서 상황에 맞는 `axios instance`를 사용하도록 수정했습니다.
- `modalAtom`을 생성하여 `Layout` 컴포넌트에 `LoginModal`을 보여주도록 구현했고, `useModal`을 훅으로 분리하여 사용하도록 했습니다.
- 로그인 유무에 따른 로그인 모달 띄움이나 에러처리는 아직 구현하지 않은 상태이고, 다음 pr에 포함하여 올리도록 하겠습니다

2024-02-02 01:40 UTC, f-lab-jake requested changes

2024-02-02 01:40 UTC, f-lab-jake commented on frontend/src/atoms/authAtom.ts
>  });
base atom의 사용을 피합시다

2024-02-02 01:40 UTC, f-lab-jake commented on frontend/src/atoms/modalAtom.ts
> +  },
그냥 `(get) => get(modalStateAtom)` 정도면 되겠죠?

2024-02-02 01:40 UTC, f-lab-jake commented on frontend/src/atoms/modalAtom.ts
> +export const modalStateAtom = atom<boolean>(false);
일단 atom에 state의 의미가 이미 있어서 state atom 이라고 하면 좀 이상합니다.
그리고 실제로 의미하는건 모달이 열린지 여부인데 그걸 나타내지 못합니다.
저같으면 `isModalOpenAtom` 정도로 하겠네요

2024-02-02 01:40 UTC, f-lab-jake commented on frontend/src/atoms/modalAtom.ts
> +export const modalAtom = atom<any, any, any>(
`any`를 안쓰는 방법을 찾아보죠. 그리고 `modalStateAtom` 그대로 쓰면 될거같은데 왜 감쌌죠?

2024-02-02 11:49 UTC, GeonwooShin commented
- useTokenApi 훅을 삭제하고 private api를 통해 관리하도록 수정했습니다
- 각각의 api 모듈은 client를 인자로 전달받습니다
- useAtomCallbacm을 사용하여 뮤테이션이 발생할때 client를 사용하도록 수정했습니다
- 따라서 로그인이 된 경우에는 client를 리턴하여 http요청이 전송되고, 비로그인인 경우에는 UnAuthorized에러가 발생하여 로그인 모달이 띄워지게됩니다

2024-02-05 08:51 UTC, GeonwooShin commented
- `query` & `mutation` 모두 `atom client` 사용을 위해 `queryFn`, `mutationFn` 콜백을 `useAtomCallback`으로 감싸 내부에서 `atom client`를 사용하도록 수정했습니다.
- `api`의 `response` 타입을 작성했습니다.

2024-02-05 10:22 UTC, f-lab-jake requested changes

2024-02-05 10:22 UTC, f-lab-jake commented on frontend/src/context/AuthContext.tsx
> +    setLocalStorage(TOKEN_KEY, token);
이 두 함수를 따로 불러야하는 상황이되면 뭔가 잘못되고 있는거겠죠?

2024-02-05 10:22 UTC, f-lab-jake commented on frontend/src/components/article/EditArticle/DukpoolEditArticle.tsx
>    const articleId = getIdFromUrl();
`getIdFromUrl`은 리액트에서 사용하면 안되는 함수입니다. 왜일까요?

2024-02-05 12:21 UTC, GeonwooShin commented on frontend/src/components/article/EditArticle/DukpoolEditArticle.tsx
>    const articleId = getIdFromUrl();
특정 React 생명주기에서 window 객체에 접근할 수 없는 경우가 있기 때문일까요?

2024-02-05 12:22 UTC, GeonwooShin commented on frontend/src/context/AuthContext.tsx
> +    setLocalStorage(TOKEN_KEY, token);
아 현재 인증로직을 jotai로 관리하면서 해당 AuthContext는 사용하지 않습니다!

삭제하도록 하겠습니다!

2024-02-05 13:22 UTC, f-lab-jake commented on frontend/src/components/article/EditArticle/DukpoolEditArticle.tsx
>    const articleId = getIdFromUrl();
접근은 늘 할수 있죠. reactive하지 않은 것이 문제입니다. 즉 url이 바뀌었을때 반응을 안합니다.

2024-02-05 14:59 UTC, GeonwooShin commented on frontend/src/components/article/EditArticle/DukpoolEditArticle.tsx
>    const articleId = getIdFromUrl();
아 그럼 react-router-dom에서 제공하는 `useParam`을 사용해야겠네요!

2024-02-05 17:31 UTC, GeonwooShin commented
- `useParam`을 사용하는 방법으로 수정
- `assert` 함수를 정의하고 url 파라미터의 타입 단언 및 `undefined`인 경우 `invalidUrlError throw`

2024-02-06 01:16 UTC, f-lab-jake commented on frontend/src/components/article/EditArticle/DukpoolEditArticle.tsx
>    const articleId = getIdFromUrl();
네네. 그리고 저 경우엔 `undefined`인 실제로 url이 그렇게 들어올수 있으므로 에러에 따로 이름을 지어줘서 핸들링 하는게 좋습니다.
`assert(articleId, new InvalidUrlError())` 이런식으로요?

2024-02-06 03:02 UTC, GeonwooShin commented on frontend/src/components/article/EditArticle/DukpoolEditArticle.tsx
>    const articleId = getIdFromUrl();
- `makeError`를 통해 `InvalidUrlError`를 생성하고 타입단언시 `InvalidError`를 인자로 함께 전달하는 방식으로 수정했습니다

2024-02-06 03:27 UTC, f-lab-jake requested changes

2024-02-06 03:27 UTC, f-lab-jake commented on frontend/src/components/search/SearchResult.tsx
> +  assert(searchId, new InvalidUrlError('InvalidUrlError'));
요걸 ErrorBoundary에서 따로 구분해서 핸들링할 필욘 없나요?

2024-02-06 05:21 UTC, GeonwooShin commented on frontend/src/components/search/SearchResult.tsx
> +  assert(searchId, new InvalidUrlError('InvalidUrlError'));
`react-router-dom`에서 `errorElement`로 유효하지 않은 URL 경로에 한해서는 `NotFound` 페이지가 렌더링되고 있습니다!

따라서 `ErrorBoundary`에서는 따로 구분해서 핸들링할 필요는 없을것같다고 생각했는데, 방지 차원에서 `ErrorBoundary`내부에서 핸들링을 진행하는게 좋을까요?

2024-02-06 06:46 UTC, f-lab-jake commented on frontend/src/components/search/SearchResult.tsx
> +  assert(searchId, new InvalidUrlError('InvalidUrlError'));
아하 router dom을 잊고있었네요. 흠 그런데 router dom이 search param에 대해서 유효성을 확인하나요?

2024-02-06 06:56 UTC, GeonwooShin commented on frontend/src/components/search/SearchResult.tsx
> +  assert(searchId, new InvalidUrlError('InvalidUrlError'));
```ts
const routes: routeElement[] = [
  {
    path: '/',
    element: <RootPage />,
    errorElement: <NotFound />,
    children: [
      { path: '', element: <Home /> },
      { path: 'article', element: <Article /> },
      { path: 'article/:articleId', element: <ArticlePost /> },
      { path: 'article/new', element: <NewArticle /> },
      { path: 'article/edit/:articleId', element: <EditArticle /> },
      { path: 'talk', element: <Talk /> },
      { path: 'talk/:talkId', element: <TalkPost /> },
      { path: 'talk/new', element: <NewTalk /> },
      { path: 'talk/edit/:talkId', element: <EditTalk /> },
      { path: 'login', element: <Login /> },
      { path: 'api/auth/kakao/callback', element: <Kakao /> },
      { path: 'mypage', element: <MyPage /> },
      { path: 'search/:searchId', element: <Search /> },
    ],
  },
];
```

위와 같이 동적라우팅을 통해 `path` 설정을 진행하고 있는데, 파라미터의 유효성에 따라서 `errorElement`가 예외처리를 담당하는 것 같습니다

https://reactrouter.com/en/main/route/error-element

2024-02-06 10:41 UTC, f-lab-jake commented on frontend/src/components/search/SearchResult.tsx
> +  assert(searchId, new InvalidUrlError('InvalidUrlError'));
아하 params가 search params를 얘기하는건줄 알았네요. 저러면 react router dom에 버그가 있지 않는한 assert에 걸릴일이 없겠죠?

[assert](https://www.npmjs.com/package/assert) 이 라이브러리는 `AssertionError`라는 구분된 에러타입을 사용합니다. 가정이 틀린경우에 뱉어야할 에러는 이 타입으로 구분해줘서 핸들링하는게 좋습니다. 왜그럴까요?

2024-02-06 12:24 UTC, GeonwooShin commented on frontend/src/components/search/SearchResult.tsx
> +  assert(searchId, new InvalidUrlError('InvalidUrlError'));
에러 구분을 통해 해당하는 에러에 따라서 핸들링 하기가 편해지고 명시적으로 어떤 상황인지 가독성이 보장되기 때문이라고 생각합니다.

2024-02-07 14:17 UTC, GeonwooShin commented
- `assert` 패키지를 설치하여 타입 단언을 진행하도록 수정했습니다.
- 기존 `authClientThrowAtom`의 네이밍을 로그인이 보장된 client atom을 나타내는 `ensuredClientAtom`로 수정했습니다.

2024-02-08 04:01 UTC, f-lab-jake requested changes

2024-02-08 04:01 UTC, f-lab-jake commented on frontend/src/atoms/authAtom.ts
> +export const ensuredClientAtom = atom((get) => {
오 멋진 이름입니다. `ensuredAuthClientAtom`이 맞지않나요?

2024-02-08 05:50 UTC, GeonwooShin commented on frontend/src/atoms/authAtom.ts
> +export const ensuredClientAtom = atom((get) => {
그게 더 명확한것네요!

2024-02-08 11:18 UTC, f-lab-jake approved these changes

2024-02-09 05:51 UTC, merged