[FE][Feat] #42/ confirm 모달 구현
f-lab-edu/dukpool pull request #44
Opened 2024-02-09 11:21 UTC by GeonwooShin

- `confirm` 모달의 전역 상태 관리를 위해 `primitive atom`과 `write atom`을 정의 했습니다. (c0f01dfb0ac1f891b79df90294523ac2d51c543d)
- 애플리케이션의 공통 레이아웃에서 `confirmModal`을 관리합니다. (cafc91cc897a5f9bc4d76e2089837d2c69343712)
- `confirmModal`의 타입을, 댓글, 게시물, 회원탈퇴로 나눠 타입에 따라 메시지를 보여주도록 구현했습니다. (37f80d9011f38d25d5e125d0b15e0fec580d82b2)
- `useConfirmModal` 훅을 생성하여 관심사 분리를 진행했습니다. (06fd1d29a253fb8c49f27f6855618d0de626b031)

다음과 같은 순서로 진행되도록 로직을 작성했습니다.

1. 게시물의 삭제 버튼을 클릭하면 `handleDelete` 함수가 실행됩니다.
2. `openModal`이 실행되고 `promise`가 생성됩니다. `promise`가 `fulfilled` 상태가 되길 기다립니다.
3. 모달이 띄워지고, 모달의 삭제 버튼을 클릭하면 `promise`가 `resolve`됩니다.
4. `handleDelete` 함수 내부에서 `openModal`의 `promise`가 `resolve`되어 `mutation`이 실행됩니다.

문제 상황
- `ConfirmModal` 컴포넌트 내에서 `useConfirmModal` 훅의 `hideModal`, `confirmModal`을 임포트하여 모달의 취소와 삭제버튼에 각각 `hideModal`, `confirmModal`을 바인딩했습니다. 게시물 컴포넌트 내에서는 `useConfirmModal`훅의 `openModal`을 임포트하여 삭제 버튼에 `openModal`을 바인딩하고 `promise`가 `fulfilled`상태가 되길 기다립니다. `resolve`된다면 `mutation`이 실행되어야 하는데, `promise`가 정상적으로 `resolve`, `reject`가 진행되지 않는것 같습니다.
- `openModal`시에 `promise`를 생성하고 `promise`의 콜백 인자인 `resolve`와 `reject`는 setState를 통해 `state`로 관리하고 있습니다.

2024-02-10 09:25 UTC, GeonwooShin commented
- `promise`를 `atom`으로 관리하여 기대 동작을 충족했습니다.
- 모달이 띄워져있는 상태로 뒤로 또는 앞으로 가기 동작 시 그대로 모달이 띄워져있는 현상을 수정하기 위해 `location`이 변경되면 모든 모달이 닫히도록 수정했습니다.
- `LoginModal`, `ConfirmModal`로 분리하여 관리하던 부분을 `Modal`로 합쳐 함께 관리할 수 있도록 수정했습니다.

2024-02-10 15:32 UTC, f-lab-jake requested changes

2024-02-10 15:32 UTC, f-lab-jake commented on frontend/src/atoms/modalAtom.ts
> +      action: 'comment' | 'post' | 'resign' | 'login';
이런 디자인은 모달 종류가 늘어날때마다 여기도 함꼐 늘어나야하지 않나요?

2024-02-10 15:32 UTC, f-lab-jake commented on frontend/src/atoms/modalAtom.ts
> +      action: 'comment' | 'post' | 'resign' | 'login';
그냥 element를 인자로 받는걸 추천합니다

2024-02-12 15:39 UTC, GeonwooShin commented
- `ModalContext`를 작성하여 사용하는 방식으로 수정했습니다

2024-02-16 07:11 UTC, GeonwooShin commented
❌ 문제 상황

기존 `ModalContext`에서 모달의 타입마다 promise를 관리하고, `Modal` 컴포넌트 또한 `props`로 `type`에 따른 분기처리를 진행하면서 type이 증가됨에 따라 관리해야 할 상태 또한 추가적으로 수정해야 하는 문제 상황 발생

✅ 해결방법

`openModal` 함수에 인자로 컴포넌트를 받아, 해당 컴포넌트 `props`에 `resolveFn`을 전달, 따라서 `ModalContext`에서 promise를 관리할 필요가 사라짐, 또한 `ModalContext`에서 배열 `state`로 모달 컴포넌트를 관리 함에 따라, 여러개의 모달을 띄울 수 있도록 구현, 범용성 증가

2024-02-16 10:29 UTC, f-lab-jake requested changes

2024-02-16 10:29 UTC, f-lab-jake commented on frontend/src/components/common/Modal/CommentModal.tsx
> +      resolveFn!(false);
여기선 `?.(false)`가 맞습니다.
`resolveFn`의 타입을 undefinable로 한건 `<CommentModal />`로 했을때 타입에러가 뜨지않게 하기 위함이었을 겁니다. 지금 반드시 `resolveFn`값이 들어오도록 강제되어 있진 않습니다.

2024-02-16 10:29 UTC, f-lab-jake commented on frontend/src/components/common/Modal/CommentModal.tsx
> +      hideModal();
`resolveFn`을 하면 자동으로 `hideModal`이 호출되도록 하는게 어떨까요?

2024-02-16 10:29 UTC, f-lab-jake commented on frontend/src/components/common/Modal/CommentModal.tsx
> +  ({ resolveFn }: { resolveFn?: (type: boolean) => Promise<boolean> }) => {
`resolveFn`이란 이름은 이 `CommentModal`을 사용하는 `ModalContext`쪽 동작에 맞춰 지은 이름입니다. `CommentModal`을 일종의 form처럼 생각해보세요. 사실 현재 설계상으론, `CommentModal`을 꼭 모달위에 띄울 필요도 없습니다. 그런측면에서 `onSubmit`이 낫다고 봅니다.

2024-02-16 12:12 UTC, GeonwooShin commented on frontend/src/components/common/Modal/CommentModal.tsx
> +      resolveFn!(false);
아 이해했습니다.

옵셔널 체이닝은 `null` 또는 `undefined`인 경우에는 아무런 동작도 하지 않고
non-null assertion은 정의되어 있다고 가정하고 강제로 호출하기 때문에 

옵셔널 체이닝이 더 안전한 호출로 동작하겠네요

2024-02-16 12:12 UTC, GeonwooShin commented on frontend/src/components/common/Modal/CommentModal.tsx
> +  ({ resolveFn }: { resolveFn?: (type: boolean) => Promise<boolean> }) => {
이해했습니다!

2024-02-16 12:22 UTC, GeonwooShin commented on frontend/src/components/common/Modal/CommentModal.tsx
> +      hideModal();
`ModalContext` 내부에서 `modal`을 배열로 관리하고 있고, `hideModal`은 `ModalContext`내부에서 관리하는 `modal` state에서 마지막 모달을 제거하는 방식으로 사용하고 있는 반면에, `resolveFn`은 모달의 `props`로 전달하고 있는데 자동으로 호출되게 하려면 어디서 둘을 엮어야할까요...?

2024-02-16 13:51 UTC, f-lab-jake commented on frontend/src/components/common/Modal/CommentModal.tsx
> +      hideModal();
`resolveFn`을 전달할때 `Promise`에서 나온 값 그대로 주지말고 `hideModal`을 뒤에 호출하도록 붙여서 주면 될거같은데요

2024-02-16 14:26 UTC, GeonwooShin commented
- `onSubmit`을 전달할 때 기존에 promise resolve 함수인 `resolveFn`만 전달하는 로직에서 `hideModal`이 함께 실행되게끔 수정했습니다.
- `onSubmit`을 사용할 때 옵셔널 체이닝을 사용하는 방법으로 수정하여 안전성을 확보했습니다

2024-02-17 08:37 UTC, GeonwooShin commented
- `resolve` & `reject`의 인자로 `boolean` 뿐만 아니라, 다른 종류의 타입 또한 받을 수 있도록 제네릭을 사용하여 여러 타입을 받을 수 있게 확장성을 높였습니다
- `onSubmit`이외에 `onAbort`를 추가로 `Modal` 컴포넌트에 `props`로 전달하여 `promise`를 `reject`할 수 있도록 수정했습니다.

2024-02-17 13:05 UTC, f-lab-jake requested changes

2024-02-17 13:05 UTC, f-lab-jake commented on frontend/src/components/common/Modal/CommentModal.tsx
> +    onAbort?.(false);
여기 `false`가 어떤 의미인가요?
별뜻없으면 그냥 `onAbort?.()` 하는걸 추천합니다.

2024-02-17 14:53 UTC, GeonwooShin commented on frontend/src/components/common/Modal/CommentModal.tsx
> +    onAbort?.(false);
```ts
  const openModal = <T extends {}>(element: React.ReactElement): Promise<T> => {
    const promiseResolver = () => {
      let resolveFn: (value: T) => void = () => {};
      let rejectFn: (value: T) => void = () => {};
      const promise: Promise<T> = new Promise((resolve, reject) => {
        resolveFn = resolve;
        rejectFn = reject;
      });
      return { promise, resolveFn, rejectFn };
    };
    const { promise, resolveFn, rejectFn } = promiseResolver();

    const modal: React.ReactElement = cloneElement(element, {
      onSubmit: (value: T) => {
        resolveFn(value);
        setModals((prev) => prev.slice(0, -1));
      },
      onAbort(value: T) {
        rejectFn(value);
        setModals((prev) => prev.slice(0, -1));
      },
    });
    setModals((prev) => [...prev, modal]);
    return promise;
  };
```

`onAbort`가 제네릭 타입의 `value`인자를 받고 있어서 reject시에 반환받을 값을 넣어주는 방식으로 사용하려고 했습니다!

```ts
    const handleDelete = async () => {
      const isDeleted = await openModal(<CommentModal />).catch((e) => e);
      if (isDeleted) {
        deleteComment(id);
      }
    };
```
사용시에는 위와 같이 사용합니다!

만약 위의 방법이 잘못되었다면 

```ts
      onAbort() {
        rejectFn();
        setModals((prev) => prev.slice(0, -1));
      },
```

이와 같이 수정해서

```ts
    const handleDelete = async () => {
      const isDeleted = await openModal(<CommentModal />).catch(() => false);
      if (isDeleted) {
        deleteComment(id);
      }
    };
```

이런식으로 `reject`시에 리턴값을 주는게 더 좋을까요?

2024-02-18 09:42 UTC, f-lab-jake commented on frontend/src/components/common/Modal/CommentModal.tsx
> +    onAbort?.(false);
아 `onAbort`에 인자가 있는건 좋은데요, 그건 에러타입인게 자연스럽습니다. 왜 abort되었는지 이유를 설명하는거죠.
그리고 그 이유가 별로 안중요할 경우엔 그냥 입력안해도되게 허용하는것도 괜찮아서 `onAbort()`를 제안드린겁니다.
그런데, 저렇게하면(인자 없는것도 허용) 타이핑이 곤란해지니까 에러 값을 하나 주는게 낫겠습니다.

2024-02-18 13:08 UTC, GeonwooShin commented on frontend/src/components/common/Modal/CommentModal.tsx
> +    onAbort?.(false);
```ts
const CommentModal = memo(({ onSubmit, onAbort }: ModalProps) => {
  const handleOutside = (e: React.MouseEvent) => {
    if (e.target !== e.currentTarget) return;
    e.stopPropagation();
    onAbort?.(new PromiseReject());
  };
  return (
    <StyledWrapper onClick={handleOutside}>
      <StyledContainer>
        <StyledCloseBtnContainer>
          <StyledCloseIcon
            src={closeIcon}
            onClick={() => onAbort?.(new PromiseReject())}
          />
        </StyledCloseBtnContainer>
        <StyledFlexContainer>
          <StyledLogoContainer>
            <StyledLogo src={alert} />
          </StyledLogoContainer>
          <StyledSpan>작성하신 댓글을 삭제하시겠어요?</StyledSpan>
          <StyledButtonContainer>
            <Button
              text="취소"
              disabled={false}
              onClick={() => onAbort?.(new PromiseReject())}
              $colorType="light"
            />
            <Button
              text="삭제"
              disabled={false}
              onClick={() => onSubmit?.(true)}
              $colorType="dark"
              error={true}
            />
          </StyledButtonContainer>
        </StyledFlexContainer>
      </StyledContainer>
    </StyledWrapper>
  );
});
```

위와 같이 인자로 에러 값을 하나 전달하는 방식으로 사용하면 될까요?!

실제 사용되는 곳은

```ts
    const handleDelete = async () => {
      const isDeleted = await openModal(<CommentModal />).catch(() => false);
      if (isDeleted) {
        deleteComment(id);
        showToast('댓글이 삭제되었습니다!');
      }
    };
```

다음과 같이 사용할 수 있을것같습니다!

2024-02-19 04:59 UTC, f-lab-jake commented on frontend/src/components/common/Modal/CommentModal.tsx
> +    onAbort?.(false);
`PromiseReject`는 좀 이상한 이름입니다. reject는 Error를 전달하는 콜백함수이지 에러 자체가 아닙니다.
일단은 뭐 `new Error()` 정도로 하면 될거같네요. 지금 그렇게 중요하진 않습니다.

2024-02-19 06:24 UTC, f-lab-jake approved these changes

2024-02-19 06:32 UTC, merged