[FE][Feat] #38/ 마이 페이지 & 태그 페이지 & 검색 페이지 구현
f-lab-edu/dukpool pull request #49
Opened 2024-02-20 16:03 UTC by GeonwooShin

### 구현사항
- 마이 페이지와 스켈레톤 UI 구현완료, 닉네임 수정 시 debounce와 useQuery의 enabled 옵션을 사용하여 닉네임 중복확인을 처리합니다. (13a6b048e8a6e2a8f7522dd44a1554485a631729)
- 태그 페이지와 스켈레톤 UI 구현 (93b47dd9163db1b368f5442d05d668ca856fddd7, f6d20508ddc47307997379acbf07d5ace4de60e5)
- 검색 페이지와 스켈레톤 UI 구현 (cf24737a437c7bafb282cea18747fea888123f6d
- 기존 덕질자랑과 덕질토크에서 상세 페이지에 관한 컴포넌트를 함께 사용하고 있던 부분을 분리하고, 공통으로 사용할 수 있는 컴포넌트는 따로 관리하도록 수정했습니다. (c2af5e12c709f8eca078fc03f0efa03776ba5194, cd2e11a34a712ea23505276886d84a1373fdc580, 3ec2252b9357e5703069745bad48bc63468666ec)

### 관련 이슈
close #38 #43 #47

2024-02-21 04:49 UTC, f-lab-jake requested changes

2024-02-21 04:49 UTC, f-lab-jake commented on frontend/src/pages/NewArticle.tsx
> +  files: (string | File)[];
요건 어떤 의도로 바꾼걸까요?

2024-02-21 14:01 UTC, GeonwooShin commented on frontend/src/pages/NewArticle.tsx
> +  files: (string | File)[];
아 실제 api와 연동하려는 수정작업을 하면서 api에 body로 전달해야하는 필드 이름이 desc와 files여서 함께 수정해줬습니다!

2024-02-22 08:45 UTC, f-lab-jake commented on frontend/src/pages/NewArticle.tsx
> +  files: (string | File)[];
음 api에 따라 바꾼거면 그럴수 있습니다. 그런데 원래 이름이 더 좋긴합니다.
`files`라고 하면 이미지 파일을 넣어야한다는 정보가 사라지죠

2024-02-22 08:45 UTC, f-lab-jake approved these changes

2024-02-22 10:12 UTC, merged