[FE][Feat] #40/낙관적 업데이트 구현 & 검색 결과 미리보기 구현
f-lab-edu/dukpool pull request #51
Opened 2024-02-27 13:07 UTC by GeonwooShin

### 구현화면

![미리보기구현](https://github.com/f-lab-edu/dukpool/assets/79186378/15285e5b-21f2-4aea-98da-920628880b30)

### 구현사항
- mutation의 onMutate, onError, onSettled 옵션을 사용하여 낙관적 업데이트를 구현했습니다. (e0a59fa162a42cedb13bf3a8af5682596a8c654a)
- 검색결과 미리보기를 구현했습니다. (6fb3f20b674a18e495eda5330c87da46911dbfed)

### 관련 이슈
close #40 #45 #41

2024-02-27 14:13 UTC, f-lab-jake requested changes

2024-02-27 14:13 UTC, f-lab-jake commented on frontend/src/components/talk/TalkDetail/TalkCommentItem.tsx
> +        deleteComment({ id, contentId });
await을 붙여야하지 않나요?
댓글 삭제에 실패해도 토스트가 뜰겁니다.

2024-02-27 14:13 UTC, f-lab-jake commented on frontend/src/components/talk/TalkDetail/TalkCommentItem.tsx
>        const isDeleted = await openModal(<CommentModal />).catch(() => false);
요건 삭제 확인을 받았다는 뜻이 맞겠쬬? `shouldDelete` 정도가 있습니다.

2024-02-27 14:13 UTC, f-lab-jake commented on frontend/src/components/talk/TalkDetail/TalkDescription.tsx
> +        else postLike(id);
함수명이 부자연스럽습니다. 서로 반대동작 같지가 않아요.
그냥 `like` / `unlike`는 어떨까요?

2024-02-27 14:31 UTC, GeonwooShin commented on frontend/src/components/talk/TalkDetail/TalkCommentItem.tsx
>        const isDeleted = await openModal(<CommentModal />).catch(() => false);
해당 state는 댓글 수정 form을 열고 닫을 때 사용하는 state입니다!

2024-02-27 14:32 UTC, GeonwooShin commented on frontend/src/components/talk/TalkDetail/TalkCommentItem.tsx
> +        deleteComment({ id, contentId });
아 이부분을 컴포넌트 말고 `mutation`의 `onSuccess`에서 처리하도록 하겠습니다!

2024-02-27 16:49 UTC, GeonwooShin commented on frontend/src/components/talk/TalkDetail/TalkDescription.tsx
> +        else postLike(id);
수정했습니다!

2024-02-29 15:43 UTC, GeonwooShin commented
### 추가 구현사항

- 현재 `ClientProvider` 에서 `defaultOptions` 로`mutation` 의 `onError` 처리를 담당하고 있는데, 낙관적업데이트를 진행하면서 `useMutation` 훅에 `onError`옵션을 지정하면서 `defaultOptions`로 지정한 `onError`가  덮어씌워지는 현상이 발생하여 기본 `mutation error` 처리를 훅으로 분리했습니다 ([86475b2](https://github.com/f-lab-edu/dukpool/pull/51/commits/86475b2fa37a0239a79ebd5c2ce02e28856e37ab), [275756f](https://github.com/f-lab-edu/dukpool/pull/51/commits/275756fa007ccca703d4d4159eb0dcaba51d784c))

- 모달이 띄워질 때 쿼리 캐시 데이터가 사라지는 현상을 `queryClient`에 `useMemo`를 사용하여 해결했습니다. ([879be2e](https://github.com/f-lab-edu/dukpool/pull/51/commits/879be2eb082d55ea49f5883ab462213a2d3720b4))

- 모달의 렌더링을 담당하는 컴포넌트를 생성하고 `ClientProvider` 보다 하위에 위치시켜 모달 컴포넌트 내에서 `queryClient`를 사용할 수 있도록 수정했습니다. ([2e7f476](https://github.com/f-lab-edu/dukpool/pull/51/commits/2e7f4769b0122da5365dc41457d5f3b08a77981d))

2024-03-01 10:10 UTC, f-lab-jake requested changes

2024-03-01 10:10 UTC, f-lab-jake commented on frontend/src/components/common/Button/KakaoLoginButton.tsx
> +      }
`https://kauth.kakao.com/oauth/authorize?client_id=${CONFIG.API_KEYS.LOGIN}&redirect_uri=${CONFIG>ENV === 'development' ? ... : ...}/api/auth/kakao/callback&response_type=code`
요런식으로 줄일수있겠죠?
그리고 `CONFIG.ENV === 'development'` 이런 플래그는 변수로 빼놓는게 실수도 덜하고 좋습니다.

2024-03-01 10:10 UTC, f-lab-jake commented on frontend/src/components/common/Skeleton/SearchSkeleton.tsx
> +import range from 'lodash/range';
bundle사이즈 줄이려고 이렇게 한건가요?

2024-03-01 10:10 UTC, f-lab-jake commented on frontend/src/components/mypage/MyPosts.tsx
> +        {articles.length && talks.length ? (
둘중 하나라도 있으면 표시해야할것 같은데요? 왜 둘다 있어야 하죠?

2024-03-01 10:10 UTC, f-lab-jake commented on frontend/src/hooks/useDeleteMutations.ts
>        queryClient.setQueryData(['article', contentId], context?.prevContent);
optimistic update를 undo하는 더 좋은 방법이 있나요? 매 뮤테이션마다 해주려면 번거로울거 같은데요

2024-03-01 11:28 UTC, GeonwooShin commented on frontend/src/components/common/Button/KakaoLoginButton.tsx
> +      }
넵 수정하겠습니다!

2024-03-01 11:29 UTC, GeonwooShin commented on frontend/src/components/common/Skeleton/SearchSkeleton.tsx
> +import range from 'lodash/range';
넵 맞습니다!

2024-03-01 11:29 UTC, GeonwooShin commented on frontend/src/components/mypage/MyPosts.tsx
> +        {articles.length && talks.length ? (
아 이부분 수정하겠습니다!

2024-03-01 11:30 UTC, GeonwooShin commented on frontend/src/hooks/useDeleteMutations.ts
>        queryClient.setQueryData(['article', contentId], context?.prevContent);
onMutate 옵션에서 리턴한 값이 onError의 인자로 들어와서 해당 인자를 통해 undo를 해결해줘야합니다 ㅠㅠ

2024-03-01 11:49 UTC, f-lab-jake commented on frontend/src/components/common/Skeleton/SearchSkeleton.tsx
> +import range from 'lodash/range';
https://www.npmjs.com/package/lodash-es
요걸 쓰는 방법도 있긴합니다.

2024-03-02 05:38 UTC, GeonwooShin commented
- lodash-es 패키지를 사용하는 방법을 채택하여 번들사이즈를 감소시켰습니다.
- 내 정보 페이지에서 게시물 유무에 대한 분기처리를 수정하고, 게시물이 없을 경우 게시물 작성 페이지로 이동할 수 있도록 수정했습니다.
- CONFIG.ENV를 변수로 분리하여 관리하도록 수정했습니다.

2024-03-02 06:57 UTC, f-lab-jake approved these changes

2024-03-03 06:54 UTC, merged